######################################################################
# Automatically generated by qmake (3.0) Mon Feb 23 22:35:09 2015
######################################################################

TEMPLATE = app
TARGET = zmatrixconverter
INCLUDEPATH += .
QT += core gui
QT += widgets

# Input
HEADERS += convertdialog.h data.h structs.h Vec3D.h
SOURCES += convertdialog.cpp data.cpp main.cpp Vec3D.cpp
